### login

POST https://plus-ui-backend.onrender.com/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test1234"
}

### Signout

### Signup
POST https://plus-ui-backend.onrender.com/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test1234"
}

### Get Profile
GET https://plus-ui-backend.onrender.com/profile/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IllxYjgrU01BT0NVZE9UYlkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2dwY2R4c2dsbnpodWd4dnl5dWhsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlOGZiZGUzMi01MjFmLTRmYWYtYjFjYi0wZjUyOWYwYjRjMTYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU2MzE4NDkxLCJpYXQiOjE3NTYzMTQ4OTEsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZThmYmRlMzItNTIxZi00ZmFmLWIxY2ItMGY1MjlmMGI0YzE2In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTYzMTQ4OTF9XSwic2Vzc2lvbl9pZCI6ImNmODMyMjdjLTExNjYtNDk3My04MDhlLTIwNmI3YzkzMTQwNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.2h6gMyDb4rsZr4rNGpc_8YR7Olio5ayqckBcaSZW2sY

### API Key Güncelle
POST https://plus-ui-backend.onrender.com/profile/api-key
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IllxYjgrU01BT0NVZE9UYlkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2dwY2R4c2dsbnpodWd4dnl5dWhsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlOGZiZGUzMi01MjFmLTRmYWYtYjFjYi0wZjUyOWYwYjRjMTYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUzNjI3MTM5LCJpYXQiOjE3NTM2MjM1MzksImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZThmYmRlMzItNTIxZi00ZmFmLWIxY2ItMGY1MjlmMGI0YzE2In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTM2MjM1Mzl9XSwic2Vzc2lvbl9pZCI6ImNlNjdhZDEzLWViZTYtNDc3Yy1iZDQxLTczZjg3N2VlMTExZSIsImlzX2Fub255bW91cyI6ZmFsc2V9.iufjNTUMI_3u_d8vbIB_PANudNK-G21CE-47uck8E_8

{
  "api_key": "ad5b2e57-77c9-4b34-9801-f8188d9a9947"
}